### ISSUE TITLE
No .env file, as stated in instructions

### ISSUE THREAD

**Issue by IgorGanapolsky** [Husseinjd/job-search-2.0#1]
Good day,
I am attempting to run your example, and your instructions say to do this:
`cp .env.example .env`

But there is no such file.  Please advise.
Igor

**Comment by Husseinjd** [comment]
Hello @IgorGanapolsky , no need to run that step, as I added recently the .env directly within the project.  
Thanks for raising the issue, I will update the readme for that step.
